import type { Metadata } from "next";
import {Assistant} from 'next/font/google'
import { ToastContainer } from 'react-toastify';
import GlobalProvider from '../components/Application/GlobalProvider'
import "./globals.css";


const assistantFont=Assistant({
  weight:['200','300','400','500','600','700','800'],
  subsets:['latin'],
  display:"swap"
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${assistantFont.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <GlobalProvider>
           {children}
        <ToastContainer/>
        </GlobalProvider>
       
        </body>
    </html>
  );
}
